---
- name: Update apt cache
  apt: update_cache=yes

- name: Install apt dependencies
  apt: name={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - nodejs
    - python-pip
    - python-dev
    - htop
    - git

- name: Install additional packages
  apt: name={{ item }}
  with_items: packages
